apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spacehub
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: spacehub-api=docker.io/fahmimrezuan/spacehub:*
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: spacehub-logs
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: ssh://git@github.com/fahmimrezuan/spacehub-infra.git
    targetRevision: HEAD
    path: spacehub/overlays


    directory:
      recurse: false

  #plugin here
  #http://c799e361-99c0-4f18-8f1c-1463c5d356cd.k8s.spacehub.local
  destination:
    server: https://kubernetes.default.svc
    namespace: spacehub

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan
    - PruneLast=true

    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
