apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

images:
- name: quay.io/argoprojlabs/argocd-image-updater
  newTag: latest

resources:
- config/
- deployment/
- rbac/
- secret/
