apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAwjuJQiiO+uM3PSk3BbDNK7W937QP0xRGAckADIhAEs9drXgMaqGrLRMYiLThLLvK9LwO7OJBqsIkI24HBKj4VUOxNAqdQ3NnGL1uabQW2MNkRAT98baW7KH3yIvl5GaPw5Ujnre8cT/KMyf3J8IYNi+JT7nOAfXJYrFQqX7SwU593cN+xRA2d4QwxhaZd6FsMvEJTxcHaUXZL1cOhVJ9MZy5DfNVUtWOL+2qY18cMTiuwDklxxxqqq22QaXjyo/d3pylH0nTpD2bM6Qy0caMvCIffyCUM01AX0PDP1he/ju8/EiYjFuiYNOzc7p1byfXMdsJpNqPk9Pu/wQe2zq+V6gm/jGsxEXlwP1r3GjDNp16qiKfRlZAFjmI4iGonss9COaMtGJeIWVs0x9GDTjCZP6Mbi8UBJ46i15u7gpD0SH5rcWH9uY/U23zWKEWRbILQZutLwb/lkWdShIZKKJE/yN/L8y0fU/sA6BQkYM09fBj0eRSIVj8J9OPTlDWj7F5ylHT3RaX3GNcm1MX1TG/V9FdUOQyRuTvRStxo/JzaLxx9+GQapcFfOOySRBI0iDv0Ur+POsjrzJmc5Xk/XEEEWXxxwwfg2DcqKeBkuoGoNxbqrm1CUtASnteKQLIOhEMHjVISwpdSlAyysUtB1Z3pOVAsmiNb2rJRYc/pSjBL75Vb5i9lAdskP2vQu+5g+61RreZyY/zst+e5LshjC3zQVry1mE0T4JuvJPdwR7VfIIMBdcKaNIXgklzFAoTc5POVxGJ2WJk3JOj79vEtjjkDGQdEZMADGNvy+C1diqlF2oZfUqNv6VPcUha2GNCGkFLiny8ile42XsWpnWiDF+MVV22ZdFKbCYmjOF5WVfmQ==
  template:
    metadata:
      creationTimestamp: null
      name: registry-secret
      namespace: argocd

