apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- namespace.yaml
- services.yaml
- ingress.yaml
- configmap.yaml
patches:
- path: be-replicas-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: spacehub-backend
images:
- name: docker.io/fahmimrezuan/spacehub
  newTag: 1.2.5

