apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacehub-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacehub-backend
  template:
    metadata:
      labels:
        app: spacehub-backend
    spec:
      containers:
      - name: spacehub-api
        image: fahmimrezuan/spacehub:1.0.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: spacehub-configmap
        - secretRef:
            name: spacehub-secret
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        ports:
        - containerPort: 8000
      # imagePullSecrets:
      # - name: docker-config-creds
